KsLogBundle:
    resource: "@KsLogBundle/Resources/config/routing.yml"
    prefix:   /

KsNewsBundle:
    resource: "@KsNewsBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
